name: Sync BOTH (inside + source<->target)

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Inside SOURCE
        env:
          YANDEX_OAUTH_TOKEN: ${{ secrets.YANDEX_OAUTH_TOKEN }}
          DISK_SOURCE_PATH: ${{ secrets.DISK_SOURCE_PATH }}
        run: python sync_inside_source.py

      - name: Wait a bit (avoid Disk lock)
        run: sleep 3

      - name: SOURCE -> TARGET (cert + tickets)
        env:
          YANDEX_OAUTH_TOKEN: ${{ secrets.YANDEX_OAUTH_TOKEN }}
          DISK_SOURCE_PATH: ${{ secrets.DISK_SOURCE_PATH }}
          DISK_TARGET_PATH: ${{ secrets.DISK_TARGET_PATH }}
        run: python sync_source_to_target.py

      - name: Wait a bit (avoid Disk lock)
        run: sleep 3

      - name: TARGET -> SOURCE (mts cert)
        env:
          YANDEX_OAUTH_TOKEN: ${{ secrets.YANDEX_OAUTH_TOKEN }}
          DISK_SOURCE_PATH: ${{ secrets.DISK_SOURCE_PATH }}
          DISK_TARGET_PATH: ${{ secrets.DISK_TARGET_PATH }}
        run: python sync_target_to_source.py
